"""Remove unique constraint from collection title

Revision ID: b172f8abb025
Revises: 997a7e8456b6
Create Date: 2023-10-13 01:10:50.994629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b172f8abb025'
down_revision = '997a7e8456b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_constraint('collection_title_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.create_unique_constraint('collection_title_key', ['title'])

    # ### end Alembic commands ###
